
;;;;TEST;;;;
(let ((x 0))
  (let ((x 1))
    (let ((x 2))
      (let ((x 3))
        (let ((x 4))
          (let ((x 5))
            (let ((x 6))
              (let ((x 7))
                (let ((x 8))
                  (let ((x 9))
                    (let ((x 10))
                      (let ((x 11))
                        (let ((x 12))
                          (let ((x 13))
                            (let ((x 14))
                              (let ((x 15))
                                (let ((x 16))
                                  (let ((x 17))
                                    (let ((x 18))
                                      (let ((x 19))
                                        (let ((x 20))
                                          (let ((x 21))
                                            (let ((x 22))
                                              (let ((x 23))
                                                (let ((x 24))
                                                  (let ((x 25))
                                                    (let ((x 26))
                                                      (let ((x 27))
                                                        (let ((x 28))
                                                          (let ((x 29))
                                                            (let ((x 30))
                                                              (let ((x 31))
                                                                (let ((x 32))
                                                                  x))))))))))))))))))))))))))))))))) ;=> 32
;;;;TEST;;;;
(let ((x 1))
  (assert x 1)
  (defun foo (x)
    (assert x 2)
    (let ((x 3))
      (assert x 3)
      x
      )))
(let ((x 4))
  (assert x 4)
  (foo 2)) ;=> 3
