#ifndef Z_OPTIONS_H
#define Z_OPTIONS_H


/* MUST BE DEFINED: */
/* #define OPTION_LOG_LEVEL_INITIALIZATION LOG_LEVEL_MAX */
#define OPTION_LOG_LEVEL_INITIALIZATION 0
#define OPTION_LOG_LEVEL_EXECUTION 6

#define OPTION_USE_READLINE 1

#define OPTION_DEBUG 1
#define OPTION_DEBUG_MEMORY 1

#define OPTION_PROGRAM_NAME "zeigen"
#define OPTION_DEFAULT_PORT 9999

#endif
