#!/bin/sh

bspc config window_gap 0
bspc config border_width 0
bspc config normal_border_color "#000000"
bspc config focused_border_color "#aa0000"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config focus_follows_pointer true

bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

./bspwm-floating &
